### ISSUE TITLE
add benchmark section

### ISSUE THREAD

**Issue by Kikobeats** [lukeed/premove#3]
it isn't exactly the same (I think `premove` doesn't support glob patterns), but do you think could be fair compare it with `del`?

https://github.com/sindresorhus/del

**Comment by lukeed** [comment]
Sure – I'd (eventually) set up a benchmark that doesn't even use glob patterns. The main feature is recursive removals, not pattern matching.

I'd also throw `rimraf` into the mix (and probably native `fs.rmdir` for fun). But TBH this is a low-ish priority for me just because the native offering exists and isn't cutting-edge anymore. Basically, `premove` exists as a lightweight solution for older Node versions, and now offers a light CLI layer. Unless candidates are doing something crazy, all items _should_ be throttled/limited by how quickly Node can execute the removals
